class_name MatchConfig extends RefCounted

## Match configuration for multiplayer battles
##
## Contains all the information needed to start and synchronize a match
## between connected peers. Generated by the host and shared with clients.

## Unique match identifier
var match_id: String = ""

## Random seed for battle RNG (shared between all peers)
var battle_seed: int = 0

## Peer ID of the match host
var host_peer_id: int = 1

## Ordered list of player peer IDs (index 0 = player 1, index 1 = player 2)
var player_peer_ids: Array[int] = []

## Ordered list of summoner IDs each player is using
var player_summoner_ids: Array[String] = []

## Deck hashes for validation (to detect cheating/desync)
var player_deck_hashes: Array[int] = []

## Unix timestamp when match was created
var created_at: float = 0.0

## Match type (for future expansion: ranked, casual, tournament)
var match_type: String = "casual"


func _init() -> void:
	created_at = Time.get_unix_time_from_system()


## Generate a unique match ID
static func generate_match_id() -> String:
	var chars: String = "abcdefghijklmnopqrstuvwxyz0123456789"
	var result: String = ""
	for _i: int in 16:
		result += chars[randi() % chars.length()]
	return result


## Generate a random battle seed
static func generate_battle_seed() -> int:
	return randi()


## Create a new match config with random values
static func create_new(host_id: int) -> RefCounted:
	var script: GDScript = load("res://scripts/multiplayer/core/match_config.gd")
	var config: RefCounted = script.new()
	config.match_id = generate_match_id()
	config.battle_seed = generate_battle_seed()
	config.host_peer_id = host_id
	return config


## Get player index (0 or 1) for a given peer ID
func get_player_index(peer_id: int) -> int:
	return player_peer_ids.find(peer_id)


## Check if a peer is in this match
func has_player(peer_id: int) -> bool:
	return peer_id in player_peer_ids


## Add a player to the match
func add_player(peer_id: int, summoner_id: String, deck_hash: int) -> void:
	player_peer_ids.append(peer_id)
	player_summoner_ids.append(summoner_id)
	player_deck_hashes.append(deck_hash)


## Serialize match config for network transmission
func serialize() -> Dictionary:
	return {
		"match_id": match_id,
		"battle_seed": battle_seed,
		"host_peer_id": host_peer_id,
		"player_peer_ids": player_peer_ids,
		"player_summoner_ids": player_summoner_ids,
		"player_deck_hashes": player_deck_hashes,
		"created_at": created_at,
		"match_type": match_type,
	}


## Deserialize match config from network data
static func deserialize(data: Dictionary) -> RefCounted:
	var script: GDScript = load("res://scripts/multiplayer/core/match_config.gd")
	var config: RefCounted = script.new()
	config.match_id = data.get("match_id", "")
	config.battle_seed = data.get("battle_seed", 0)
	config.host_peer_id = data.get("host_peer_id", 1)

	# Handle typed array conversion
	var peer_ids: Array = data.get("player_peer_ids", [])
	config.player_peer_ids = []
	for id: Variant in peer_ids:
		config.player_peer_ids.append(int(id))

	var summoner_ids: Array = data.get("player_summoner_ids", [])
	config.player_summoner_ids = []
	for id: Variant in summoner_ids:
		config.player_summoner_ids.append(str(id))

	var deck_hashes: Array = data.get("player_deck_hashes", [])
	config.player_deck_hashes = []
	for hash_val: Variant in deck_hashes:
		config.player_deck_hashes.append(int(hash_val))

	config.created_at = data.get("created_at", 0.0)
	config.match_type = data.get("match_type", "casual")
	return config
